# Generated by Django 5.0.4 on 2024-04-21 18:14

import django.db.models.deletion
import phone_field.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('svg', models.TextField(blank=True, default="<svg xmlns='http://www.w3.org/2000/svg' width='40' fill='currentColor' class='bi bi-calendar4-event' viewBox='0 0 16 16'><path d='M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5M2 2a1 1 0 0 0-1 1v1h14V3a1 1 0 0 0-1-1zm13 3H1v9a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1z'/><path d='M11 7.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5z'/></svg>")),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('-title',),
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image1', models.ImageField(blank=True, upload_to='uploads/venue')),
                ('image2', models.ImageField(blank=True, upload_to='uploads/venue')),
                ('image3', models.ImageField(blank=True, upload_to='uploads/venue')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='Venue type')),
                ('location', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('fb_link', models.CharField(blank=True, max_length=255, verbose_name='facebook link')),
                ('ig_link', models.CharField(blank=True, max_length=255)),
                ('x_link', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(default='Add venue description')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, upload_to='uploads/events')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('starting_time', models.TimeField()),
                ('church_or_group', models.CharField(max_length=100)),
                ('group_logo', models.ImageField(blank=True, upload_to='uploads/group_logos')),
                ('district', models.CharField(max_length=100)),
                ('conference', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('post_event', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.venue')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
