# Generated by Django 5.0.4 on 2024-04-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_churchorgroup_remove_event_group_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchorgroup',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
