# Generated by Django 5.0.4 on 2024-04-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image1',
            field=models.ImageField(blank=True, default='./static/images/defaults/Location_icon_from_Noun_Project.png', null=True, upload_to='uploads/venue'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image2',
            field=models.ImageField(blank=True, default='./static/images/defaults/location-pin-vector-icon-2.jpg', null=True, upload_to='uploads/venue'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image3',
            field=models.ImageField(blank=True, default='./static/images/defaults/location-pin-vector-icon.jpg', null=True, upload_to='uploads/venue'),
        ),
    ]
