# Generated by Django 5.0.4 on 2024-05-05 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_venue_created_by_alter_venue_image1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchorgroup',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='church_or_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.churchorgroup'),
        ),
    ]
