# Generated by Django 5.0.4 on 2024-05-07 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_churchorgroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchorgroup',
            name='fb_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='facebook link'),
        ),
        migrations.AddField(
            model_name='churchorgroup',
            name='ig_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='instagram link'),
        ),
        migrations.AddField(
            model_name='churchorgroup',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='churchorgroup',
            name='x_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='x link'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.venue'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='ig_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='instagram link'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='x_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='x link'),
        ),
    ]
