# Generated by Django 5.0.4 on 2024-05-09 13:28

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_venuetype_options_alter_venue_venue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
