# Generated by Django 5.0.4 on 2024-06-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_county_event_county_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ('name',), 'verbose_name_plural': 'Counties'},
        ),
        migrations.AddField(
            model_name='county',
            name='slug',
            field=models.SlugField(default='None'),
        ),
    ]
