# Generated by Django 5.0.4 on 2024-06-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_county_options_county_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='slug',
            field=models.SlugField(),
        ),
    ]
