# Generated by Django 5.0.4 on 2024-04-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('starting_time', models.TimeField()),
                ('church_or_group', models.CharField(max_length=100)),
                ('church_or_group_logo', models.ImageField(upload_to='')),
                ('district', models.CharField(max_length=100)),
                ('conference', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
