# Generated by Django 5.0.4 on 2024-04-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='church_or_group_logo',
        ),
    ]
