# Generated by Django 5.0.4 on 2024-04-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='starting_date',
        ),
    ]
