# Generated by Django 5.0.4 on 2024-04-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_date_event_starting_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
