# Generated by Django 5.0.4 on 2024-05-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('postal_address', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('ig_link', models.CharField(max_length=255)),
                ('fb_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('svg', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, upload_to='uploads/profile')),
                ('position', models.CharField(max_length=100)),
                ('linkedin_link', models.CharField(max_length=255)),
                ('ig_link', models.CharField(max_length=255)),
                ('fb_link', models.CharField(max_length=255)),
                ('x_link', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='about',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='uploads/about/banner'),
        ),
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='services_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='logo',
            field=models.ImageField(blank=True, upload_to='uploads/about/group_logos'),
        ),
        migrations.AddField(
            model_name='about',
            name='contacts',
            field=models.ManyToManyField(to='about.contact'),
        ),
        migrations.AddField(
            model_name='about',
            name='services',
            field=models.ManyToManyField(blank=True, to='about.services'),
        ),
        migrations.AddField(
            model_name='about',
            name='team',
            field=models.ManyToManyField(blank=True, to='about.teammember'),
        ),
    ]
