# Generated by Django 5.0.4 on 2024-05-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_contact_services_teammember_about_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fb_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ig_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='fb_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='ig_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='x_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
