# Generated by Django 5.0.4 on 2023-11-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_contact_fb_link_alter_contact_ig_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='about.contact'),
        ),
    ]
