# Generated by Django 5.0.4 on 2024-05-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('position',)},
        ),
    ]
